namespace SpriteKind {
    export const Tree = SpriteKind.create()
    export const Water = SpriteKind.create()
    export const Fire = SpriteKind.create()
}
function levelThree () {
	
}
function level_one () {
    info.setScore(0)
    scene.setBackgroundColor(9)
    scene.setBackgroundImage(img`
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................................................................................................................................................................
        ................bbbbbbbbb.......................................................................................................................................
        .........bbbbbbbbbbbbbbbbbbb....................................................................................................................................
        ....bbbbbbbbeebbbeeeebbbbbbbbbbbbbbbbbbbbbbbb...................................................................................................................
        .eeebbbbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbb................................................................................................................
        bbbbbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeebbbbbbbb..........................................................................................................
        ebbeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbb.....................................................................................................
        ebeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbeeebbbbbbbbbb...............................................................................................
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb...........................................................................................
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbb..................................................................................bbb
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbb.............................................bbbbbbbbbbbb.....................bbbe
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbb..................................bbbbbbbbbbbbbbbbbbb..........bbbbbbbbbee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbeebbbbbbbbbbbbbbbbbbbbbbbeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbeebbbbbeeeebbbbbeebbbbbbbbbbbbbbeeeeebbbbeeeebbbbbbbbbbbbbbbbeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeebbbeeebeeeeeeeeeeeeebeeeeeeeebeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
        `)
    getPlayer = sprites.create(img`
        ............................
        ............................
        ..........444444............
        ........4444444444..........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .....4444444444444444.......
        .......dddddddddddd.........
        .......dddfddddfddd.........
        .......dddddddddddd.........
        ........dddddddddd..........
        ..........ddddddd...........
        .........22ddddd22..........
        ........22222222222.........
        .......2222222222222........
        .......2222222222222........
        .......2222222222222........
        .......2222222222222........
        ......dddfffffffffddd.......
        .........222222222..........
        .........222...222..........
        ........2222...2222.........
        .......22222...22222........
        ............................
        ............................
        `, SpriteKind.Player)
    getPlayer.ay = 0
    getPlayer.ax = 0
    controller.moveSprite(getPlayer, 60, 60)
    scene.cameraFollowSprite(getPlayer)
    animation.runImageAnimation(
    getPlayer,
    [img`
        ..........4444114...........
        .........444444414..........
        ........4444444441..........
        ........44444444444.........
        ........55555555555.........
        .......4444444444444........
        .........ddddddddd44........
        .........ddddfddfd..........
        .........ddddddddd..........
        ..........ddddddd...........
        .........22222222...........
        .......22222222221..........
        .......222222222221.........
        ......22212222222221........
        ......22221222222222dd......
        ......22222dd2222222dbbb....
        ........222dbbbbbbbbbb......
        .......bbbbbb2222...........
        ......bb.ffffcfff...........
        ......b..22222222...........
        ......bb.22222222...........
        .......bb2222.2222..........
        ........b2222.2222..........
        .........2222.2222..........
        .........2222.2222..........
        ........2222...222..........
        ........2222...222..........
        ........fffff..ffff.........
        `,img`
        ..........4444114...........
        .........444444414..........
        ........4444444441..........
        ........44444444444.........
        ........55555555555.........
        .......4444444444444........
        .........ddddfddfd44........
        .........ddddfddfd..........
        .........ddddddddd..........
        ..........ddddddd...........
        .........22222222...........
        ........2222222221..........
        .......222222222221.........
        ......22212222222221........
        ......22221222222222dd......
        ......22222dd2222222dbbb....
        ........222dd22bbbbbbb......
        .......bbbbbbbbb2...........
        ......bb.ffffcfff...........
        ......b..222222222..........
        ......bb.222222222..........
        .......bb2222.2222..........
        ........b2222..222..........
        .........2222..222..........
        ........2222..2222..........
        ........2222..2222..........
        ........222...2222..........
        ........ffff..fffff.........
        `],
    1000,
    true
    )
    playerFace = 0
    init()
    info.startCountdown(90)
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    getPlayer,
    [img`
        ...........4444114..........
        ..........444444414.........
        ..........4444444414........
        .........44444444444........
        .........55555555555........
        ........4444444444444.......
        ........44dfddfdddd.........
        ..........dfddfdddd.........
        ..........ddddddddd.........
        ...........ddddddd..........
        ...........22222222.........
        ..........12222222222.......
        .........122222222222.......
        ........12222222221222......
        ......dd22222222212222......
        ....bbbd2222222dd22222......
        ......bbbbbbbbbbd222........
        ...........2222bbbbbb.......
        ...........fffcffff.bb......
        ...........22222222..b......
        ...........22222222.bb......
        ..........2222.2222bb.......
        ..........2222.2222b........
        ..........2222.2222.........
        ..........2222.2222.........
        ..........222...2222........
        ..........222...2222........
        .........ffff..fffff........
        `,img`
        ...........4444114..........
        ..........444444414.........
        ..........4444444414........
        .........44444444444........
        .........55555555555........
        ........4444444444444.......
        ........44dfddfdddd.........
        ..........dfddfdddd.........
        ..........ddddddddd.........
        ...........ddddddd..........
        ...........22222222.........
        ..........1222222222........
        .........122222222222.......
        ........12222222221222......
        ......dd22222222212222......
        ....bbbd22222222122222......
        ......bbbbbbb22dd222........
        ...........2bbbdbbbbb.......
        ...........fffcffff.bb......
        ...........22222222..b......
        ...........22222222.bb......
        ..........2222.2222bb.......
        ..........2222.2222b........
        ..........222..2222.........
        ..........2222..222.........
        ..........2222..2222........
        ...........222..2222........
        ..........ffff.fffff........
        `],
    1000,
    true
    )
    playerFace = 1
})
info.onCountdownEnd(function () {
    getPlayer.startEffect(effects.spray, 500)
    getPlayer.sayText("即將進入下一關!")
    currentLevel = currentLevel + 1
    totalScore = info.score()
    info.setScore(0)
    pause(2000)
    newLevel()
})
function init () {
    tiles.setCurrentTilemap(tilemap`層級2`)
    treeList = tiles.getTilesByType(sprites.castle.tileGrass2)
    for (let value of tiles.getTilesByType(sprites.castle.tileGrass2)) {
        tree_icon = sprites.create(img`
            .....77777..........
            ..777777177.........
            .77774777717........
            7777774777447.......
            77447477444717......
            7774477774777.......
            .77744774444771.....
            .7774447447777......
            ..777744477776......
            ..77.77447766.......
            ......44466.........
            ......4444..........
            ......4444..........
            ......4444..........
            .....44444..........
            .....44444..........
            .....4444...........
            ....44444...........
            ....44444...........
            .....44444..........
            `, SpriteKind.Tree)
        tiles.placeOnTile(tree_icon, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
    for (let value of tiles.getTilesByType(sprites.castle.tilePath3)) {
        tree_icon = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . 6 6 . . . . . . 1 1 . . 
            . . . . 1 7 6 . . . . 1 7 6 . . 
            . . . 1 7 7 7 6 . . 1 7 7 6 . . 
            . . 6 7 6 6 7 7 6 1 7 7 6 . . . 
            . . 6 6 . . 6 7 6 7 7 6 . . . . 
            . . . . . . 6 7 6 7 6 . . . . . 
            . . . . . . 6 7 7 6 . . . . . . 
            . . . . . . . 7 7 6 . . . . . . 
            . . . . . . . 6 6 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Tree)
        tiles.placeOnTile(tree_icon, value)
        tiles.setTileAt(value, assets.tile`transparency16`)
    }
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    getPlayer,
    [img`
        ..........b.................
        ..........b.................
        .........bbb................
        .........b444414............
        .........44444414...........
        ........444444441...........
        .......b4444444444..........
        ......d45444444441..........
        ......2b4544445544..........
        ......2bd4555544d...........
        ......22224444222...........
        ......222222222222..........
        .......222222221222.........
        .......b22222221222.........
        ........b222222212..........
        .........2222222............
        .........2222222............
        .........bff22ff............
        ........bb2ffff2............
        .......bb2222222............
        ........b222.222............
        .........222.2222...........
        .........222.2222...........
        .........222.2222...........
        .........22f.2f22...........
        .........fff.ffff...........
        .........ff..ff.............
        ............................
        `,img`
        ..........bb................
        ..........bb................
        .........bbb................
        .........b444414............
        .........44444414...........
        ........444444441...........
        ........4444444444..........
        ......d45444444441..........
        ......2b4544445544..........
        ......2bd4555544d...........
        ......22224444222...........
        .......22222222222..........
        .......222222221222.........
        .......b22222221222.........
        ........b222222212..........
        .........22222222...........
        .........2222222............
        .........bff22ff............
        ........bb2ffff2............
        .......bb2222222............
        ........b222.2222...........
        .........222.2222...........
        .........222.2222...........
        .........222.2222...........
        .........22f.2f22...........
        .........fff.ffff...........
        .........ff...fff...........
        ............................
        `],
    1000,
    true
    )
    playerFace = 0
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    controller.moveSprite(getPlayer, 0, 0)
    getPlayer.setVelocity(0, 0)
    if (playerFace == 0) {
        water = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Water)
        water.setPosition(getPlayer.x - 4, getPlayer.top - 38)
        animation.runImageAnimation(
        water,
        [img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....9...........
            ......9....9....
            ....9......9....
            .....96..96.....
            ......66.66.....
            ......96969.....
            ......96669.....
            .......6668.....
            .......6668.....
            .......668......
            .......668......
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ........9.......
            ................
            ......9..9......
            ....9...9.......
            .......9.99.....
            .....9.9.9......
            ......9.69......
            ......9.69......
            .....9.66.......
            ......969.......
            ......969.......
            ......966.......
            .......666......
            .......966......
            .......9668.....
            ......66668.....
            ......6668......
            .......668......
            ......96668.....
            ......96668.....
            ......96668.....
            ......9668......
            .......668......
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ............9...
            ................
            ................
            .....99.........
            ......9.9.......
            .....9..9.9.....
            ...9...99....9..
            .....9.9.9......
            ......96....9...
            ......96........
            .....9669.......
            ......66.9......
            ......6669......
            .....9.669......
            .....9966.......
            ......96669.....
            ......96669.....
            ......96669.....
            ......96668.....
            ......96668.....
            ......96668.....
            ........66......
            .......6699.....
            .......669......
            ......9669......
            ......9669......
            ......86669.....
            ......96669.....
            ......96669.....
            ......9666......
            .......666......
            .......966......
            .......9668.....
            ......66668.....
            ......6668......
            .......668......
            ......96668.....
            ......96668.....
            ......96668.....
            ......9668......
            .......668......
            `],
        200,
        true
        )
        pause(800)
        water.destroy()
    } else if (playerFace == 1) {
        water = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Water)
        water.setPosition(getPlayer.left - 32, getPlayer.y)
        animation.runImageAnimation(
        water,
        [img`
            ................................................
            ................................................
            ................................................
            .................................99.............
            ................................................
            ..............................99.9999...........
            ..........................9.9996666666999999999.
            ..............................666666666666666666
            .........................9..9...9999886666666666
            ........................9.99..........8888888888
            .......................9.........9..............
            ................................................
            ................................................
            ................................................
            ................................................
            ................................................
            `,img`
            ................................................
            ................................................
            ................................................
            ................................................
            ................................................
            ...........................9999999999...........
            .................9...9999..66666666666999999999.
            ..................999.66666666666666666666666666
            ..................9.6666666666..8888666666666666
            ................999..8888888..........8888888888
            .....................99.........................
            ...............9.8..99..........................
            ..................9.............................
            ................................................
            ................................................
            ................................................
            `,img`
            ................................................
            ................................................
            ................................................
            ................................................
            ...................999..........................
            ...........................9999999999...........
            ................999999999..66666666666999999999.
            ............999966666666666666666666666666666666
            ........9999666666666666666666..8888666666666666
            .......9.66666666666.8888888..........8888888888
            .....99...8888888...............................
            .........9...9..................................
            .........9..9...................................
            ......9.........................................
            .........9......................................
            ................................................
            `],
        200,
        true
        )
        pause(800)
        water.destroy()
    } else if (playerFace == 2) {
        water = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Water)
        water.setPosition(getPlayer.x - 3, getPlayer.bottom)
        animation.runImageAnimation(
        water,
        [img`
            .......668......
            .......668......
            .......6668.....
            .......6668.....
            ......96669.....
            ......96969.....
            ......66.66.....
            .....96..96.....
            ....9......9....
            ......9....9....
            ....9...........
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            `,img`
            .......668......
            ......9668......
            ......96668.....
            ......96668.....
            ......96668.....
            .......668......
            ......6668......
            ......66668.....
            .......9668.....
            .......966......
            .......666......
            ......966.......
            ......969.......
            ......969.......
            .....9.66.......
            ......9.69......
            ......9.69......
            .....9.9.9......
            .......9.99.....
            ....9...9.......
            ......9..9......
            ................
            ........9.......
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            `,img`
            .......668......
            ......9668......
            ......96668.....
            ......96668.....
            ......96668.....
            .......668......
            ......6668......
            ......66668.....
            .......9668.....
            .......966......
            .......666......
            ......9666......
            ......96669.....
            ......96669.....
            ......86669.....
            ......9669......
            ......9669......
            .......669......
            .......6699.....
            ........66......
            ......96668.....
            ......96668.....
            ......96668.....
            ......96669.....
            ......96669.....
            ......96669.....
            .....9966.......
            .....9.669......
            ......6669......
            ......66.9......
            .....9669.......
            ......96........
            ......96....9...
            .....9.9.9......
            ...9...99....9..
            .....9..9.9.....
            ......9.9.......
            .....99.........
            ................
            ................
            ............9...
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            `],
        200,
        true
        )
        pause(800)
        water.destroy()
    } else if (playerFace == 3) {
        water = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.Water)
        water.setPosition(getPlayer.right, getPlayer.y + 3)
        animation.runImageAnimation(
        water,
        [img`
            ................................................
            ................................................
            ................................................
            .............99.................................
            ................................................
            ...........9999.99..............................
            .9999999996666666999.9..........................
            666666666666666666..............................
            6666666666889999...9..9.........................
            8888888888..........99.9........................
            ..............9.........9.......................
            ................................................
            ................................................
            ................................................
            ................................................
            ................................................
            `,img`
            ................................................
            ................................................
            ................................................
            ................................................
            ................................................
            ...........9999999999...........................
            .99999999966666666666..9999...9.................
            66666666666666666666666666.999..................
            6666666666668888..6666666666.9..................
            8888888888..........8888888..999................
            .........................99.....................
            ..........................99..8.9...............
            .............................9..................
            ................................................
            ................................................
            ................................................
            `,img`
            ................................................
            ................................................
            ................................................
            ................................................
            ..........................999...................
            ...........9999999999...........................
            .99999999966666666666..999999999................
            666666666666666666666666666666669999............
            6666666666668888..6666666666666666669999........
            8888888888..........8888888.66666666666.9.......
            ...............................8888888...99.....
            ..................................9...9.........
            ...................................9..9.........
            .........................................9......
            ......................................9.........
            ................................................
            `],
        200,
        true
        )
        pause(800)
        water.destroy()
    }
    controller.moveSprite(getPlayer, 60, 60)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    getPlayer,
    [img`
        ..........4444114...........
        .........444444414..........
        ........4444444441..........
        ........44444444444.........
        ........55555555555.........
        .......4444444444444........
        .........ddddfddfd44........
        .........ddddfddfd..........
        .........ddddddddd..........
        ..........ddddddd...........
        .........22222222...........
        .......22222222221..........
        .......222222222221.........
        ......22212222222221........
        ......22221222222222dd......
        ......22222dd2222222dbbb....
        ........222dbbbbbbbbbb......
        .......bbbbbb2222...........
        ......bb.ffffcfff...........
        ......b..22222222...........
        ......bb.22222222...........
        .......bb2222.2222..........
        ........b2222.2222..........
        .........2222.2222..........
        .........2222.2222..........
        ........2222...222..........
        ........2222...222..........
        ........fffff..ffff.........
        `,img`
        ..........4444114...........
        .........444444414..........
        ........4444444441..........
        ........44444444444.........
        ........55555555555.........
        .......4444444444444........
        .........ddddfddfd44........
        .........ddddfddfd..........
        .........ddddddddd..........
        ..........ddddddd...........
        .........22222222...........
        ........2222222221..........
        .......222222222221.........
        ......22212222222221........
        ......22221222222222dd......
        ......22222dd2222222dbbb....
        ........222dd22bbbbbbb......
        .......bbbbbbbbb2...........
        ......bb.ffffcfff...........
        ......b..222222222..........
        ......bb.222222222..........
        .......bb2222.2222..........
        ........b2222..222..........
        .........2222..222..........
        ........2222..2222..........
        ........2222..2222..........
        ........222...2222..........
        ........ffff..fffff.........
        `],
    1000,
    true
    )
    playerFace = 3
})
sprites.onOverlap(SpriteKind.Water, SpriteKind.Fire, function (sprite, otherSprite) {
    otherSprite.destroy()
    music.baDing.play()
    info.setScore(info.score() + 1)
})
function newLevel () {
    if (currentLevel == 1) {
        level_one()
    } else if (currentLevel == 2) {
        levelTwo()
    } else if (currentLevel == 3) {
        levelThree()
    } else {
        info.setScore(totalScore)
        game.over(true, effects.confetti)
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    getPlayer,
    [img`
        ............................
        .........44444..............
        ........4444414.............
        .......444444414............
        ......44444444414...........
        ......444444444414..........
        ......455555555444..........
        .......4444444444...........
        ........ddfddfdd............
        ........ddfddfdd............
        .........dddddd.............
        ........22dddd2.............
        .......222222222bb..........
        .......2222222222b..........
        ......22212222122b..........
        ......2221222ddbb...........
        ......2221222bbd............
        .......22212bbf2............
        .......2221bb22.............
        .......2ddbbcfff............
        ........ddb22222............
        .........bb2.222............
        ........bb22..22............
        .........222..22............
        .........222..22............
        .........ff2.22f............
        .........fff.fff............
        ............................
        `,img`
        ............................
        .........44444..............
        ........4444414.............
        .......444444414............
        ......44444444414...........
        ......444444444414..........
        ......455555555444..........
        .......4444444444...........
        ........ddfddfdd............
        ........ddfddfdd............
        .........dddddd.............
        ........22dddd2.............
        .......222222222b...........
        .......2222222222b..........
        ......22212222122b..........
        ......2221222ddbbb..........
        ......2221222bbd............
        ......222212bbf2............
        .......2221bb22.............
        .......22d2bcfff............
        ........2ddb2222............
        .........dd2.222............
        .........bb2..22............
        .........b22..22............
        .........222..22............
        .........ff2..2f............
        .........fff..ff............
        ............................
        `],
    1000,
    true
    )
    playerFace = 2
})
function levelTwo () {
    mySprite = sprites.create(img`
        ............................
        ............................
        ..........444444............
        ........4444444444..........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .......444444444444.........
        .....4444444444444444.......
        .......dddddddddddd.........
        .......dddfddddfddd.........
        .......dddddddddddd.........
        ........dddddddddd..........
        ..........ddddddd...........
        .........22ddddd22..........
        ........22222222222.........
        .......2222222222222........
        .......2222222222222........
        .......2222222222222........
        .......2222222222222........
        ......dddfffffffffddd.......
        .........222222222..........
        .........222...222..........
        ........2222...2222.........
        .......22222...22222........
        ............................
        ............................
        `, SpriteKind.Player)
    controller.player2.moveSprite(mySprite)
}
let fire_random: tiles.Location = null
let fire: Sprite = null
let mySprite: Sprite = null
let water: Sprite = null
let tree_icon: Sprite = null
let treeList: tiles.Location[] = []
let playerFace = 0
let getPlayer: Sprite = null
let totalScore = 0
let currentLevel = 0
currentLevel = 1
totalScore = 0
newLevel()
game.onUpdateInterval(4000, function () {
    fire = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . 2 . . . . . 
        . . 2 . . . . . . 2 2 2 . . . . 
        . . 2 2 . . . . 2 2 2 2 . . . . 
        . . 2 2 2 . . . 2 2 4 2 2 . . . 
        . 2 2 4 2 2 . 2 2 4 4 2 . . . . 
        . 2 4 4 2 2 2 2 2 4 4 2 . . . . 
        . 2 4 4 4 2 2 2 4 4 4 2 . . . . 
        . 2 4 4 4 2 2 2 4 4 4 2 2 . . . 
        . 2 4 4 4 4 4 4 4 4 4 2 2 . . . 
        . 2 4 4 4 4 4 4 4 5 4 4 2 . . . 
        2 4 4 4 5 4 4 4 5 5 4 4 2 . . . 
        2 2 4 4 5 5 4 5 5 5 4 4 2 2 . . 
        2 2 4 4 5 5 5 5 5 5 4 4 2 2 . . 
        2 2 4 4 5 5 5 5 5 5 5 4 2 2 . . 
        2 2 4 5 5 5 5 5 5 5 5 4 4 2 . . 
        `, SpriteKind.Fire)
    fire_random = treeList[randint(0, treeList.length - 1)]
    tiles.placeOnTile(fire, fire_random)
    animation.runImageAnimation(
    fire,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 2 . . . . . . . 
        . . . . . 2 . 2 2 . . . . . . . 
        . . . . . . . 2 4 2 . . . . . . 
        . . . . . . 2 4 4 2 . . . . . . 
        . . . 2 . 2 4 4 5 4 2 . . . . . 
        . . . . . 4 4 5 5 5 4 . . . . . 
        . . . . 2 4 5 5 5 5 4 2 . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 2 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 2 . . . . . . . 
        . . . . . . . . 2 2 . . . . . . 
        . . . . . . . 2 2 2 . . . . . . 
        . . . . 2 . 2 2 4 2 . . . . . . 
        . . . . 2 . 2 2 4 4 2 . . 2 . . 
        . . . . . 2 2 4 4 4 2 . . 2 . . 
        . . 2 . . 2 4 4 5 4 2 2 . . . . 
        . . . . 2 2 4 5 5 4 4 2 . . . . 
        . . . 2 2 4 4 5 5 5 4 2 2 . . . 
        . . 2 2 4 4 5 5 5 5 4 4 2 2 . . 
        . . . 2 4 5 5 5 5 5 5 4 2 . . . 
        `,img`
        . . . . . . . . 2 . . . . . . . 
        . . . . . . . . 2 . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . 2 . . . 2 . . . . . . . 
        . . . . 2 . . 2 2 2 . . . . . . 
        . . . . . . 2 2 2 2 . . . . . . 
        . . 2 . . 2 2 2 4 2 2 . . 2 . . 
        . . . . 2 2 2 4 4 4 2 . . 2 . . 
        . . . 2 2 2 4 4 4 4 2 2 . . . . 
        . . . 2 2 4 4 4 5 4 4 2 2 . . . 
        2 . 2 2 4 4 4 5 5 4 4 2 2 . . . 
        . . 2 4 4 4 5 5 5 5 4 4 2 2 . 2 
        . 2 2 4 4 4 5 5 5 5 4 4 2 2 . 2 
        2 2 4 4 4 5 5 5 5 5 5 4 2 2 2 . 
        2 4 4 4 5 5 5 5 5 5 5 4 4 2 2 . 
        . 2 4 4 5 5 5 5 5 5 5 5 2 2 . . 
        `],
    500,
    true
    )
})
